### ISSUE TITLE
NameError: name 'audiofile' is not defined

### ISSUE THREAD

**Issue by adalmieres** [FlorinAndrei/soundspec#11]
I have this error when executing the script.

Traceback (most recent call last):
  File "soundspec.py", line 839, in <module>
    main()
  File "soundspec.py", line 47, in main
    task.process()
  File "soundspec.py", line 93, in process
    num_errors = self.__process_files_single_process(audio_files)
  File "soundspec.py", line 134, in __process_files_single_process
    num_errors += self.process_file(audiofile)
  File "soundspec.py", line 153, in process_file
    spectrogram_creator.create(audiofile, sf, bw, audio)
  File "soundspec.py", line 355, in create
    num_errors, Sxxnew = self.__scale_down(freqs.size, findex, Sxx)
  File "soundspec.py", line 438, in __scale_down
    num_errors = self.__downscale_sanity_check(num_freqs, findex, findex_begin, findex_end)
  File "soundspec.py", line 474, in __downscale_sanity_check
    self.logger.log_message(audiofile + ': findex[' + str(i) + ']: begin error')
NameError: name 'audiofile' is not defined

the command used is :
C:\Users\aaa\Box> python soundspec.py "C:\Users\aaa\Box\audioFile.mp3"

I have the same error in batch mode with :
python soundspec.py -b "C:\Users\aaa\Box"
or
python soundspec.py -b "C:\Users\aaa\Box\*.mp3"
or
python soundspec.py "C:\Users\aaa\Box\*.mp3"
....

**Comment by StroepWafel** [comment]
same
